version: '3.8'

services:
  # Сервис для разработки
  nuxt-dev:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: nuxt-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.nuxt
    environment:
      - NUXT_PUBLIC_GRAPHQL_HTTP=https://wp.chinpoko.ru/graphql
      - NUXT_PUBLIC_GRAPHQL_WS=wss://wp.chinpoko.ru/graphql
      - NODE_ENV=development
      - NUXT_HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    command: sh -c "npm install && npm run dev"
    tty: true
    stdin_open: true

  # Сервис для продакшена с SSR
  nuxt-prod:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    container_name: nuxt-prod
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - NUXT_PUBLIC_GRAPHQL_HTTP=https://wp.chinpoko.ru/graphql
      - NUXT_PUBLIC_GRAPHQL_WS=wss://wp.chinpoko.ru/graphql
      - NODE_ENV=production
      - NITRO_HOST=0.0.0.0
      - NITRO_PORT=3000
    command: node .output/server/index.mjs
