version: '3.8'

services:
  nuxt:
    image: node:22-alpine
    container_name: nuxt-dev
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev -- --port=3000 --hostname=0.0.0.0"
    restart: unless-stopped
